### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sunhuaiqiang** [dvm-shlee/bruker#1]
I got 
ERROR: Could not find a version that satisfies the requirement shleeh>=0.0.4 (from bruker==0.3.2rc0) (from versions: 0.0.1.dev1)
ERROR: No matching distribution found for shleeh>=0.0.4 (from bruker==0.3.2rc0)
when I run
pip install bruker
OR
pip install git+https://github.com/dvm-shlee/bruker

**Comment by dvm-shlee** [comment]
@sunhuaiqiang 
Thank you for open this issue, I was not aware I did not update the dependent module.
It should work now, could you try 
pip install --upgrade shleeh bruker

**Comment by sunhuaiqiang** [comment]
it works,  cool!

**Comment by dvm-shlee** [comment]
@sunhuaiqiang Good to hear that it worked well! Then, I will close this issue.

BTW, I just found more issues today and fixed it as much as possible, and so far, the 0.3.2 released version is the most stable version. Please let me know if you have any issues while using this module! Thanks!
